name: 'Update cfgitbot config'
on:
  push:
    paths:
      - '*.tf'
      - '*.tfstate'
      - '*.tfvars'
  schedule:
    - cron: '0/5 0 * * *'

jobs:
  update_config:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.7
    - name: Update repository list
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        terraform init
        terraform apply -auto-approve -no-color
        if [[ -n $(git status -s) ]]; then
          git config user.name bosh-admin-bot
          git config user.email dap-tas-journey-bosh-ecosystem@vmware.com
          git add .
          git commit -m "Update terraform state"
          git push
        fi
